package mango

import (
	"fmt"
	"strconv"
	"strings"

	"axctl/pkg/ipc"
)

type Generator struct{}

func NewGenerator() *Generator {
	return &Generator{}
}

func mangoConfigColor(s string) string {
	if s == "" {
		return "0x000000ff"
	}
	c := ipc.MangoColor(s)
	if c == "" {
		return "0x000000ff"
	}
	return c
}

func formatMangoModifiers(mods []string) string {
	if len(mods) == 0 {
		return ""
	}
	var mapped []string
	for _, m := range mods {
		upper := strings.ToUpper(m)
		switch upper {
		case "SUPER", "MOD4", "WIN":
			mapped = append(mapped, "SUPER")
		case "CTRL", "CONTROL":
			mapped = append(mapped, "CTRL")
		case "ALT":
			mapped = append(mapped, "ALT")
		case "SHIFT":
			mapped = append(mapped, "SHIFT")
		default:
			mapped = append(mapped, upper)
		}
	}
	return strings.Join(mapped, "+")
}

var mangoDispatchers = map[string]string{
	"exec":                 "spawn",
	"spawn":                "spawn",
	"close":                "killclient",
	"killclient":           "killclient",
	"fullscreen":           "togglefullscreen",
	"togglefullscreen":     "togglefullscreen",
	"maximize":             "togglemaximizescreen",
	"togglemaximizescreen": "togglemaximizescreen",
	"togglefloating":       "togglefloating",
	"toggle-floating":      "togglefloating",
	"pin":                  "toggleglobal",
	"toggleglobal":         "toggleglobal",
	"toggle-pin":           "toggleglobal",
	"reload":               "reload_config",
	"reload_config":        "reload_config",
	"quit":                 "quit",
	"exit":                 "quit",
	"focusdir-left":        "focusdir left",
	"focusdir-right":       "focusdir right",
	"focusdir-up":          "focusdir up",
	"focusdir-down":        "focusdir down",
	"smartmovewin-left":    "smartmovewin left",
	"smartmovewin-right":   "smartmovewin right",
	"smartmovewin-up":      "smartmovewin up",
	"smartmovewin-down":    "smartmovewin down",
	"center":               "centerwin",
	"centerwin":            "centerwin",
	"toggle-scratchpad":    "toggle_scratchpad",
	"toggle_scratchpad":    "toggle_scratchpad",
	"switch-layout":        "switch_layout",
	"switch_layout":        "switch_layout",
	"setlayout":            "setlayout",
	"incnmaster":           "incnmaster",
	"setmfact":             "setmfact",
	"zoom":                 "zoom",
	"focusmon-left":        "focusmon left",
	"focusmon-right":       "focusmon right",
	"focusmon-up":          "focusmon up",
	"focusmon-down":        "focusmon down",
	"focusmon-next":        "focusmon right",
	"focusmon-prev":        "focusmon left",
	"tagmon-left":          "tagmon left",
	"tagmon-right":         "tagmon right",
	"tagmon-up":            "tagmon up",
	"tagmon-down":          "tagmon down",
	"viewtoleft":           "viewtoleft",
	"viewtoright":          "viewtoright",
	"focusstack-next":      "focusstack next",
	"focusstack-prev":      "focusstack prev",
	"focusstack":           "focusstack next",
	"groupfocus-next":      "groupfocus next",
	"groupfocus-prev":      "groupfocus prev",
	"minimize":             "minimized",
	"minimized":            "minimized",
	"restore-minimized":    "restore_minimized",
	"toggleoverview":       "toggleoverview",
	"togglejump":           "togglejump",
	"togglefakefullscreen": "togglefakefullscreen",
	"toggleoverlay":        "toggleoverlay",
}

func mangoMapDispatcher(d string) string {
	if d == "" {
		return "spawn"
	}
	if v, ok := mangoDispatchers[strings.ToLower(d)]; ok {
		return v
	}
	return d
}

func boolStr(b *bool) string {
	if b == nil {
		return ""
	}
	if *b {
		return "1"
	}
	return "0"
}

func intStr(i *int) string {
	if i == nil {
		return ""
	}
	return strconv.Itoa(*i)
}

func floatStr(f *float64) string {
	if f == nil {
		return ""
	}
	return strconv.FormatFloat(*f, 'f', -1, 64)
}

func (g *Generator) GenerateAppearance(config ipc.ConfigAppearance) string {
	var b strings.Builder
	b.WriteString("# Generated by axctl\n")
	b.WriteString("# Include this file from your mango config via `source`.\n\n")

	if config.Gaps != nil {
		if v := intStr(config.Gaps.Inner); v != "" {
			b.WriteString("gappih = " + v + "\n")
			b.WriteString("gappiv = " + v + "\n")
		}
		if v := intStr(config.Gaps.Outer); v != "" {
			b.WriteString("gappoh = " + v + "\n")
			b.WriteString("gappov = " + v + "\n")
		}
	}

	if config.Border != nil {
		if v := intStr(config.Border.Width); v != "" {
			b.WriteString("borderpx = " + v + "\n")
		}
		if config.Border.ActiveColor != nil {
			b.WriteString("focuscolor = " + mangoConfigColor(*config.Border.ActiveColor) + "\n")
		}
		if config.Border.InactiveColor != nil {
			b.WriteString("bordercolor = " + mangoConfigColor(*config.Border.InactiveColor) + "\n")
		}
		if v := intStr(config.Border.Rounding); v != "" {
			b.WriteString("border_radius = " + v + "\n")
		}
	}

	if config.Opacity != nil {
		if v := floatStr(config.Opacity.Active); v != "" {
			b.WriteString("focused_opacity = " + v + "\n")
		}
		if v := floatStr(config.Opacity.Inactive); v != "" {
			b.WriteString("unfocused_opacity = " + v + "\n")
		}
	}

	if config.Blur != nil {
		if v := boolStr(config.Blur.Enabled); v != "" {
			b.WriteString("blur = " + v + "\n")
		}
		if v := intStr(config.Blur.Size); v != "" {
			b.WriteString("blur_params_radius = " + v + "\n")
		}
		if v := intStr(config.Blur.Passes); v != "" {
			b.WriteString("blur_params_num_passes = " + v + "\n")
		}
	}

	if config.Shadow != nil {
		if v := boolStr(config.Shadow.Enabled); v != "" {
			b.WriteString("shadows = " + v + "\n")
		}
	}

	if config.Animations != nil && config.Animations.Enabled != nil {
		b.WriteString(fmt.Sprintf("animations = %s\n", boolStr(config.Animations.Enabled)))
	}

	if config.Layout != nil && *config.Layout != "" {
		b.WriteString("# layout switch via setlayout (use Config.SetLayout or keybinds)\n")
	}
	return b.String()
}

func (g *Generator) GenerateKeybinds(config ipc.ConfigKeybinds) string {
	var b strings.Builder
	b.WriteString("# Generated by axctl (keybinds)\n")
	b.WriteString("# Mango bind syntax: bind=MOD1+MOD2,KEY,COMMAND,ARGS\n\n")

	addBind := func(kb ipc.Keybind, comment string) {
		if !kb.Enabled || kb.Key == "" {
			return
		}
		mods := formatMangoModifiers(kb.Modifiers)
		dispatcher := mangoMapDispatcher(kb.Dispatcher)
		arg := kb.Argument

		key := strings.ToUpper(kb.Key)
		flags := ""
		if kb.Flags != "" {
			flags = strings.ToLower(kb.Flags) + ","
		}

		line := fmt.Sprintf("bind%s = %s,%s,%s", flags, mods, key, dispatcher)
		if strings.TrimSpace(arg) != "" {
			line += "," + arg
		}
		if comment != "" {
			line += " # " + comment
		}
		b.WriteString(line + "\n")
	}

	if config.Ambxst != nil {
		if config.Ambxst.System != nil {
			for name, kb := range config.Ambxst.System {
				addBind(kb, "Ambxst System: "+name)
			}
		}
		if config.Ambxst.Binds != nil {
			for name, kb := range config.Ambxst.Binds {
				addBind(kb, "Ambxst: "+name)
			}
		}
	}
	if config.Custom != nil {
		for i, kb := range config.Custom {
			addBind(kb, fmt.Sprintf("Custom Bind %d", i))
		}
	}
	return b.String()
}

func (g *Generator) GenerateWindowRules(rules []ipc.WindowRule) string {
	var b strings.Builder
	b.WriteString("# Generated by axctl (window rules)\n")
	b.WriteString("# Mango windowrule syntax: windowrule=PARAM:VALUE,PARAM:VALUE\n\n")

	for _, r := range rules {
		var params []string
		if r.Match != "" {
			matchParts := strings.SplitN(r.Match, ":", 2)
			if len(matchParts) == 2 {
				prop := matchParts[0]
				if prop == "class" {
					prop = "appid"
				}
				params = append(params, fmt.Sprintf("%s:%s", prop, matchParts[1]))
			} else {
				params = append(params, "appid:"+r.Match)
			}
		}
		if r.Float != nil {
			params = append(params, "isfloating:"+boolStr(r.Float))
		}
		if r.NoBlur != nil {
			params = append(params, "noblur:"+boolStr(r.NoBlur))
		}
		if r.NoShadow != nil {
			params = append(params, "isnoshadow:"+boolStr(r.NoShadow))
		}
		if v := intStr(r.Rounding); v != "" {
			params = append(params, "isnoradius:0")
		}
		if v := intStr(r.BorderSize); v != "" {
			_ = v
		}
		if r.Pin != nil {
			params = append(params, "isglobal:"+boolStr(r.Pin))
		}
		if r.Fullscreen != nil {
			params = append(params, "isfullscreen:"+boolStr(r.Fullscreen))
		}
		if r.IdleInhibit != nil {
			params = append(params, "idleinhibit_when_focus:"+boolStr(r.IdleInhibit))
		}
		if r.Move != nil && *r.Move != "" {
			params = append(params, "offsetx:"+*r.Move)
		}
		if r.Size != nil && *r.Size != "" {
			params = append(params, "width:"+*r.Size)
		}
		if r.Rule != "" {
			params = append(params, r.Rule)
		}
		if len(params) == 0 {
			continue
		}
		b.WriteString("windowrule = " + strings.Join(params, ",") + "\n")
	}
	return b.String()
}

func (g *Generator) GenerateLayerRules(rules []ipc.LayerRule) string {
	return "# Layer rules not supported in mango\n"
}

func (g *Generator) GenerateStartup(exec []string, execOnce []string) string {
	if len(exec) == 0 && len(execOnce) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("# Generated by axctl (startup)\n\n")
	for _, cmd := range execOnce {
		if strings.TrimSpace(cmd) == "" {
			continue
		}
		b.WriteString("exec-once = " + cmd + "\n")
	}
	for _, cmd := range exec {
		if strings.TrimSpace(cmd) == "" {
			continue
		}
		b.WriteString("exec = " + cmd + "\n")
	}
	return b.String()
}
