package niri

import (
	"fmt"
	"strings"

	"axctl/pkg/ipc"
)

type Generator struct{}

// NewGenerator returns a new instance of the Niri config generator
func NewGenerator() *Generator {
	return &Generator{}
}

func formatNiriColor(hexStr string) string {
	if hexStr == "" {
		return "#00000000"
	}
	if strings.HasPrefix(hexStr, "#") {
		return hexStr
	}
	return "#" + hexStr
}

func parseNiriColorString(str string) []string {
	if str == "" {
		return nil
	}
	parts := strings.Fields(str)
	var colors []string

	for _, part := range parts {
		if !strings.HasSuffix(part, "deg") {
			colors = append(colors, formatNiriColor(part))
		}
	}

	return colors
}

func (g *Generator) GenerateAppearance(config ipc.ConfigAppearance) string {
	var out strings.Builder

	out.WriteString("// Generated by axctl ConfigGenerator\n")
	out.WriteString("// Do not edit manually!\n\n")

	out.WriteString("layout {\n")
	if config.Gaps != nil && config.Gaps.Inner != nil {
		out.WriteString(fmt.Sprintf("    gaps %d\n", *config.Gaps.Inner))
	}

	if config.Border != nil {
		out.WriteString("    border {\n")
		if config.Border.Width != nil {
			out.WriteString(fmt.Sprintf("        width %d\n", *config.Border.Width))
		}
		if config.Border.ActiveColor != nil {
			colors := parseNiriColorString(*config.Border.ActiveColor)
			if len(colors) > 0 {
				out.WriteString(fmt.Sprintf("        active-color \"%s\"\n", colors[0]))
			}
		}
		if config.Border.InactiveColor != nil {
			colors := parseNiriColorString(*config.Border.InactiveColor)
			if len(colors) > 0 {
				out.WriteString(fmt.Sprintf("        inactive-color \"%s\"\n", colors[0]))
			}
		}
		out.WriteString("    }\n")
	}
	out.WriteString("}\n\n")

	// niri has no global background-color in layout; it's a window-rule opacity
	// or the compositor background. Emit a comment placeholder.
	if config.Opacity != nil && config.Opacity.Inactive != nil {
		out.WriteString("// opacity.inactive not directly supported by niri layout\n")
	}

	if config.Animations != nil && config.Animations.Enabled != nil {
		out.WriteString("animations {\n")
		if !*config.Animations.Enabled {
			out.WriteString("    // Animations disabled via axctl config mapping\n")
		}
		out.WriteString("}\n")
	}

	// Rounding is applied per-window via a window-rule (geometry-corner-radius).
	if config.Border != nil && config.Border.Rounding != nil {
		out.WriteString("\nwindow-rule {\n")
		out.WriteString("    geometry-corner-radius ")
		out.WriteString(fmt.Sprintf("%d\n", *config.Border.Rounding))
		out.WriteString("    clip-to-geometry true\n")
		out.WriteString("}\n")
	}

	return out.String()
}

func formatModifiers(mods []string) string {
	if len(mods) == 0 {
		return ""
	}
	var mapped []string
	for _, m := range mods {
		switch m {
		case "SUPER":
			mapped = append(mapped, "Mod")
		case "CTRL":
			mapped = append(mapped, "Ctrl")
		case "ALT":
			mapped = append(mapped, "Alt")
		case "SHIFT":
			mapped = append(mapped, "Shift")
		default:
			mapped = append(mapped, m)
		}
	}
	return strings.Join(mapped, "+")
}

// mapNiriDispatcher translates a Hyprland-style dispatcher into a niri action.
// Returns the niri action string (without the trailing semicolon).
func mapNiriDispatcher(dispatcher, argument string) string {
	switch dispatcher {
	case "exec":
		return fmt.Sprintf("spawn \"%s\"", argument)
	case "killactive":
		return "close-window"
	case "movefocus":
		switch argument {
		case "l":
			return "focus-column-left"
		case "r":
			return "focus-column-right"
		case "u":
			return "focus-window-up"
		case "d":
			return "focus-window-down"
		}
		return "focus-column-left"
	case "movewindow":
		switch argument {
		case "l":
			return "move-column-left"
		case "r":
			return "move-column-right"
		case "u":
			return "move-window-up"
		case "d":
			return "move-window-down"
		}
		return "move-column-left"
	case "workspace":
		// workspace N or workspace +N/-N
		if strings.HasPrefix(argument, "+") || strings.HasPrefix(argument, "-") {
			return fmt.Sprintf("focus-workspace %s", argument)
		}
		return fmt.Sprintf("focus-workspace %s", argument)
	case "movetoworkspace", "movetoworkspacesilent":
		return fmt.Sprintf("move-window-to-workspace %s", argument)
	case "togglespecialworkspace":
		return "" // not supported on niri
	case "fullscreen":
		return "fullscreen-window"
	case "togglefloating":
		return "toggle-window-floating"
	case "layoutmsg":
		// Hyprland layoutmsg: colresize, promote, togglefit, swapcol, movecoltoworkspace
		switch {
		case strings.HasPrefix(argument, "colresize"):
			return "set-column-width"
		case argument == "promote":
			return "maximize-column"
		case argument == "togglefit":
			return "maximize-column"
		case strings.HasPrefix(argument, "swapcol"):
			return "move-column-left"
		case strings.HasPrefix(argument, "movecoltoworkspace"):
			return "move-window-to-workspace"
		}
		return ""
	default:
		// Pass through unknown dispatchers as-is (niri action names).
		if argument != "" {
			return fmt.Sprintf("%s %s", dispatcher, argument)
		}
		return dispatcher
	}
}

// GenerateKeybindsFromPayload renders a niri binds{} block from a batch payload.
// Unbinds are handled implicitly: rewriting the whole ambxst.kdl drops old binds.
func GenerateKeybindsFromPayload(payload ipc.BatchKeybindsPayload) string {
	var out strings.Builder
	out.WriteString("// Generated by axctl (Ambxst keybinds)\n")
	out.WriteString("// Do not edit manually!\n\n")
	out.WriteString("binds {\n")

	for _, b := range payload.Binds {
		if !b.Enabled || b.Key == "" {
			continue
		}
		combo := formatModifiers(b.Modifiers)
		if len(combo) > 0 {
			combo += "+"
		}
		combo += b.Key

		action := mapNiriDispatcher(b.Dispatcher, b.Argument)
		if action == "" {
			continue // unsupported action, skip
		}
		out.WriteString(fmt.Sprintf("    %s { %s; }\n", combo, action))
	}

	out.WriteString("}\n")
	return out.String()
}

func (g *Generator) GenerateKeybinds(config ipc.ConfigKeybinds) string {
	var out strings.Builder
	out.WriteString("// Generated by axctl ConfigGenerator (Keybinds)\n")
	out.WriteString("// Do not edit manually!\n\n")
	out.WriteString("binds {\n")

	addBind := func(kb ipc.Keybind, comment string) {
		if !kb.Enabled || kb.Key == "" {
			return
		}

		combo := formatModifiers(kb.Modifiers)
		if len(combo) > 0 {
			combo += "+"
		}
		combo += kb.Key

		dispatcher := kb.Dispatcher
		if dispatcher == "" {
			dispatcher = "exec"
		}
		arg := kb.Argument

		action := ""
		if dispatcher == "exec" {
			action = fmt.Sprintf("spawn \"%s\"", arg)
		} else {
			action = dispatcher
			if arg != "" {
				action += fmt.Sprintf(" %s", arg)
			}
		}

		line := fmt.Sprintf("    %s { %s; }", combo, action)
		if comment != "" {
			line += fmt.Sprintf(" // %s", comment)
		}
		out.WriteString(line + "\n")
	}

	if config.Ambxst != nil {
		if config.Ambxst.System != nil {
			for name, kb := range config.Ambxst.System {
				addBind(kb, fmt.Sprintf("Ambxst System: %s", name))
			}
		}
		if config.Ambxst.Binds != nil {
			for name, kb := range config.Ambxst.Binds {
				addBind(kb, fmt.Sprintf("Ambxst: %s", name))
			}
		}
	}

	if config.Custom != nil {
		for i, kb := range config.Custom {
			addBind(kb, fmt.Sprintf("Custom Bind %d", i))
		}
	}

	out.WriteString("}\n")
	return out.String()
}

func (g *Generator) GenerateWindowRules(rules []ipc.WindowRule) string {
	var out strings.Builder
	out.WriteString("// Generated by axctl ConfigGenerator (Window Rules)\n")
	out.WriteString("// Do not edit manually!\n\n")

	// niri uses `window-rule` (singular) blocks, not a `window-rules` container.
	for _, r := range rules {
		if r.Match != "" && r.Rule != "" {
			out.WriteString("window-rule {\n")
			out.WriteString(fmt.Sprintf("    match %s\n", r.Match))
			out.WriteString(fmt.Sprintf("    %s\n", r.Rule))
			out.WriteString("}\n\n")
		}
	}

	return out.String()
}

func (g *Generator) GenerateLayerRules(rules []ipc.LayerRule) string {
	var out strings.Builder
	out.WriteString("// Generated by axctl ConfigGenerator (Layer Rules)\n")
	out.WriteString("// Do not edit manually!\n\n")

	// niri supports layer-rule with background-effect { blur true }.
	// Map Hyprland-style layer rules (namespace + blur) to niri layer-rule blocks.
	for _, r := range rules {
		if r.Namespace == "" {
			continue
		}
		out.WriteString("layer-rule {\n")
		out.WriteString(fmt.Sprintf("    match namespace=\"%s\"\n", r.Namespace))
		if r.Blur != nil && *r.Blur {
			out.WriteString("    background-effect {\n")
			out.WriteString("        blur true\n")
			out.WriteString("    }\n")
		}
		out.WriteString("}\n\n")
	}

	return out.String()
}

func (g *Generator) GenerateStartup(exec []string, execOnce []string) string {
	var out strings.Builder
	out.WriteString("// Generated by axctl ConfigGenerator (Startup)\n")
	out.WriteString("// Do not edit manually!\n\n")

	for _, cmd := range execOnce {
		out.WriteString(fmt.Sprintf("spawn-at-startup \"%s\"\n", cmd))
	}
	for _, cmd := range exec {
		out.WriteString(fmt.Sprintf("spawn-at-startup \"%s\"\n", cmd))
	}

	return out.String()
}
