package niri

import (
	"fmt"
	"strings"

	"axctl/pkg/ipc"
)

type Generator struct{}

// NewGenerator returns a new instance of the Niri config generator
func NewGenerator() *Generator {
	return &Generator{}
}

func formatNiriColor(hexStr string) string {
	if hexStr == "" {
		return "#00000000"
	}
	if strings.HasPrefix(hexStr, "#") {
		return hexStr
	}
	return "#" + hexStr
}

func parseNiriColorString(str string) []string {
	if str == "" {
		return nil
	}
	parts := strings.Fields(str)
	var colors []string

	for _, part := range parts {
		if !strings.HasSuffix(part, "deg") {
			colors = append(colors, formatNiriColor(part))
		}
	}

	return colors
}

func (g *Generator) GenerateAppearance(config ipc.ConfigAppearance) string {
	var out strings.Builder

	out.WriteString("// Generated by axctl ConfigGenerator\n")
	out.WriteString("// Do not edit manually!\n\n")

	out.WriteString("layout {\n")
	if config.Gaps != nil && config.Gaps.Inner != nil {
		out.WriteString(fmt.Sprintf("    gaps %d\n", *config.Gaps.Inner))
	}
	
	if config.Border != nil {
		out.WriteString("    border {\n")
		if config.Border.Width != nil {
			out.WriteString(fmt.Sprintf("        width %d\n", *config.Border.Width))
		}
		if config.Border.ActiveColor != nil {
			colors := parseNiriColorString(*config.Border.ActiveColor)
			if len(colors) > 0 {
				out.WriteString(fmt.Sprintf("        active-color \"%s\"\n", colors[0]))
			}
		}
		if config.Border.InactiveColor != nil {
			colors := parseNiriColorString(*config.Border.InactiveColor)
			if len(colors) > 0 {
				out.WriteString(fmt.Sprintf("        inactive-color \"%s\"\n", colors[0]))
			}
		}
		out.WriteString("    }\n")
	}
	out.WriteString("}\n\n")

	if config.Animations != nil && config.Animations.Enabled != nil {
		out.WriteString("animations {\n")
		// niri typically has something like off or on, we'll keep it simple
		if !*config.Animations.Enabled {
			out.WriteString("    // Animations disabled via axctl config mapping\n")
			out.WriteString("    // Currently Niri might not have a global disable, but we signify it here.\n")
		}
		out.WriteString("}\n")
	}

	return out.String()
}

func formatModifiers(mods []string) string {
	if len(mods) == 0 {
		return ""
	}
	var mapped []string
	for _, m := range mods {
		switch m {
		case "SUPER":
			mapped = append(mapped, "Mod")
		case "CTRL":
			mapped = append(mapped, "Ctrl")
		case "ALT":
			mapped = append(mapped, "Alt")
		case "SHIFT":
			mapped = append(mapped, "Shift")
		default:
			mapped = append(mapped, m)
		}
	}
	return strings.Join(mapped, "+")
}

func (g *Generator) GenerateKeybinds(config ipc.ConfigKeybinds) string {
	var out strings.Builder
	out.WriteString("// Generated by axctl ConfigGenerator (Keybinds)\n")
	out.WriteString("// Do not edit manually!\n\n")
	out.WriteString("binds {\n")

	addBind := func(kb ipc.Keybind, comment string) {
		if !kb.Enabled || kb.Key == "" {
			return
		}
		
		combo := formatModifiers(kb.Modifiers)
		if len(combo) > 0 {
			combo += "+"
		}
		combo += kb.Key

		dispatcher := kb.Dispatcher
		if dispatcher == "" {
			dispatcher = "exec"
		}
		arg := kb.Argument
		
		action := ""
		if dispatcher == "exec" {
			action = fmt.Sprintf("spawn \"%s\"", arg)
		} else {
			action = dispatcher
			if arg != "" {
				action += fmt.Sprintf(" %s", arg)
			}
		}

		line := fmt.Sprintf("    %s { %s; }", combo, action)
		if comment != "" {
			line += fmt.Sprintf(" // %s", comment)
		}
		out.WriteString(line + "\n")
	}

	if config.Ambxst != nil {
		if config.Ambxst.System != nil {
			for name, kb := range config.Ambxst.System {
				addBind(kb, fmt.Sprintf("Ambxst System: %s", name))
			}
		}
		if config.Ambxst.Binds != nil {
			for name, kb := range config.Ambxst.Binds {
				addBind(kb, fmt.Sprintf("Ambxst: %s", name))
			}
		}
	}

	if config.Custom != nil {
		for i, kb := range config.Custom {
			addBind(kb, fmt.Sprintf("Custom Bind %d", i))
		}
	}

	out.WriteString("}\n")
	return out.String()
}

func (g *Generator) GenerateWindowRules(rules []ipc.WindowRule) string {
	var out strings.Builder
	out.WriteString("// Generated by axctl ConfigGenerator (Window Rules)\n")
	out.WriteString("// Do not edit manually!\n\n")
	out.WriteString("window-rules {\n")

	for _, r := range rules {
		if r.Match != "" && r.Rule != "" {
			out.WriteString(fmt.Sprintf("    match %s {\n", r.Match))
			out.WriteString(fmt.Sprintf("        %s\n", r.Rule)) // simplistic approach
			out.WriteString("    }\n")
		}
	}

	out.WriteString("}\n")
	return out.String()
}


func (g *Generator) GenerateLayerRules(rules []ipc.LayerRule) string {
	var out strings.Builder
	out.WriteString("// Generated by axctl ConfigGenerator (Layer Rules)\n")
	out.WriteString("// Do not edit manually!\n\n")
	// Niri doesn't have layer rules in the same way as Hyprland
	// Output a comment indicating this
	out.WriteString("// Layer rules not supported in Niri\n")
	return out.String()
}