package niri

import (
	"fmt"
	"strconv"
	"strings"

	"axctl/pkg/ipc"
)

type Generator struct{}

func NewGenerator() *Generator {
	return &Generator{}
}

func niriKdlColor(hexStr string) string {
	if hexStr == "" {
		return ""
	}
	hexStr = strings.TrimPrefix(hexStr, "#")
	switch len(hexStr) {
	case 6:
		return "#" + hexStr + "ff"
	case 8:
		return "#" + hexStr
	case 3:
		r := string([]byte{hexStr[0], hexStr[0], hexStr[1], hexStr[1], hexStr[2], hexStr[2], 'f', 'f'})
		return "#" + r
	case 4:
		r := string([]byte{hexStr[0], hexStr[0], hexStr[1], hexStr[1], hexStr[2], hexStr[2], hexStr[3], hexStr[3]})
		return "#" + r
	}
	return "#" + hexStr
}

func niriFirstColor(s string) string {
	parts := strings.Fields(s)
	for _, p := range parts {
		if strings.HasSuffix(p, "deg") {
			continue
		}
		return niriKdlColor(p)
	}
	return ""
}

func formatNiriModifiers(mods []string) string {
	if len(mods) == 0 {
		return ""
	}
	var mapped []string
	for _, m := range mods {
		switch strings.ToUpper(m) {
		case "SUPER":
			mapped = append(mapped, "Mod")
		case "CTRL", "CONTROL":
			mapped = append(mapped, "Ctrl")
		case "ALT":
			mapped = append(mapped, "Alt")
		case "SHIFT":
			mapped = append(mapped, "Shift")
		default:
			mapped = append(mapped, m)
		}
	}
	return strings.Join(mapped, "+")
}

func kdlQuote(s string) string {
	if s == "" {
		return "\"\""
	}
	if !strings.ContainsAny(s, " \t\"\\{}#\n") {
		return "\"" + s + "\""
	}
	escaped := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\t", `\t`).Replace(s)
	return "\"" + escaped + "\""
}

var niriDispatchers = map[string]string{
	"exec":                         "spawn",
	"spawn":                        "spawn",
	"close":                        "close-window",
	"close-window":                 "close-window",
	"fullscreen":                   "fullscreen-window",
	"fullscreen-window":            "fullscreen-window",
	"maximize":                     "maximize-window",
	"maximize-window":              "maximize-window",
	"unmaximize":                   "unmaximize-window",
	"unmaximize-window":            "unmaximize-window",
	"toggle-floating":              "toggle-window-floating",
	"togglefloating":               "toggle-window-floating",
	"toggle-window-floating":       "toggle-window-floating",
	"focus-column-left":            "focus-column-left",
	"focus-column-right":           "focus-column-right",
	"focus-window-up":              "focus-window-up",
	"focus-window-down":            "focus-window-down",
	"focus-workspace-up":           "focus-workspace-up",
	"focus-workspace-down":         "focus-workspace-down",
	"focus-monitor-left":           "focus-monitor-left",
	"focus-monitor-right":          "focus-monitor-right",
	"focus-monitor-up":             "focus-monitor-up",
	"focus-monitor-down":           "focus-monitor-down",
	"move-column-left":             "move-column-left",
	"move-column-right":            "move-column-right",
	"move-window-up":               "move-window-up",
	"move-window-down":             "move-window-down",
	"quit":                         "quit",
	"do-screen-transition":         "do-screen-transition",
	"switch-preset-column-width":   "switch-preset-column-width",
	"switch-preset-window-height":  "switch-preset-window-height",
	"reset-window-height":          "reset-window-height",
	"center-column":                "center-column",
	"center-window":                "center-window",
	"consume-window-into-column":   "consume-window-into-column",
	"expel-window-from-column":     "expel-window-from-column",
	"toggle-column-tabbed-display": "toggle-column-tabbed-display",
}

func niriMapDispatcher(d string) string {
	if d == "" {
		return "spawn"
	}
	if v, ok := niriDispatchers[d]; ok {
		return v
	}
	return d
}

func (g *Generator) GenerateAppearance(config ipc.ConfigAppearance) string {
	var b strings.Builder
	b.WriteString("// Generated by axctl\n")
	b.WriteString("// Include this file from your niri config with: include \"<this-file>\"\n\n")

	hasLayout := false
	if config.Gaps != nil && config.Gaps.Inner != nil {
		if !hasLayout {
			b.WriteString("layout {\n")
			hasLayout = true
		}
		b.WriteString(fmt.Sprintf("    gaps %d\n", *config.Gaps.Inner))
	}
	if config.Border != nil {
		if !hasLayout {
			b.WriteString("layout {\n")
			hasLayout = true
		}
		hasBorderContent := false
		if config.Border.Width != nil {
			if !hasBorderContent {
				b.WriteString("    border {\n")
				hasBorderContent = true
			}
			b.WriteString(fmt.Sprintf("        width %d\n", *config.Border.Width))
		}
		if config.Border.ActiveColor != nil {
			color := niriFirstColor(*config.Border.ActiveColor)
			if color != "" {
				if !hasBorderContent {
					b.WriteString("    border {\n")
					hasBorderContent = true
				}
				b.WriteString(fmt.Sprintf("        active-color %s\n", kdlQuote(color)))
			}
		}
		if config.Border.InactiveColor != nil {
			color := niriFirstColor(*config.Border.InactiveColor)
			if color != "" {
				if !hasBorderContent {
					b.WriteString("    border {\n")
					hasBorderContent = true
				}
				b.WriteString(fmt.Sprintf("        inactive-color %s\n", kdlQuote(color)))
			}
		}
		if hasBorderContent {
			b.WriteString("    }\n")
		}
	}
	if hasLayout {
		b.WriteString("}\n\n")
	}

	unsupported := []string{}
	if config.Gaps != nil && config.Gaps.Outer != nil {
		unsupported = append(unsupported, "outer gaps (use inner gaps in niri)")
	}
	if config.Border != nil && config.Border.Rounding != nil {
		unsupported = append(unsupported, "border rounding (niri uses per-app window-rule geometry-corner-radius)")
	}
	if config.Opacity != nil {
		unsupported = append(unsupported, "opacity (niri uses per-app window-rule opacity)")
	}
	if config.Blur != nil {
		unsupported = append(unsupported, "blur (configure via blur {} block at top level in niri)")
	}
	if config.Shadow != nil {
		unsupported = append(unsupported, "shadow (configure per-app via window-rule shadow {})")
	}
	if len(unsupported) > 0 {
		b.WriteString(fmt.Sprintf("// Not supported in niri static config: %s\n\n", strings.Join(unsupported, "; ")))
	}

	if config.Animations != nil && config.Animations.Enabled != nil {
		if *config.Animations.Enabled {
			b.WriteString("animations {\n")
		} else {
			b.WriteString("animations {\n    off\n}\n")
		}
	}
	if config.Layout != nil && *config.Layout != "" {
		b.WriteString(fmt.Sprintf("// layout switch to %q is not supported by niri (it uses continuous scrolling)\n", *config.Layout))
	}
	return b.String()
}

func (g *Generator) GenerateKeybinds(config ipc.ConfigKeybinds) string {
	var b strings.Builder
	b.WriteString("// Generated by axctl (keybinds)\n\n")
	b.WriteString("binds {\n")

	addBind := func(kb ipc.Keybind, comment string) {
		if !kb.Enabled || kb.Key == "" {
			return
		}
		combo := formatNiriModifiers(kb.Modifiers)
		if combo != "" {
			combo += "+"
		}
		combo += kb.Key

		dispatcher := niriMapDispatcher(kb.Dispatcher)
		arg := kb.Argument

		if kb.Flags != "" {
			b.WriteString(fmt.Sprintf("    %s repeat=false {\n", combo))
		} else {
			b.WriteString(fmt.Sprintf("    %s {\n", combo))
		}

		if dispatcher == "spawn" {
			parts := tokenizeShell(arg)
			if len(parts) == 0 {
				parts = []string{arg}
			}
			b.WriteString("        spawn")
			for _, p := range parts {
				b.WriteString(" " + kdlQuote(p))
			}
			b.WriteString("\n")
		} else {
			b.WriteString("        " + dispatcher)
			if arg != "" {
				if i, err := strconv.Atoi(arg); err == nil {
					b.WriteString(fmt.Sprintf(" %d", i))
				} else {
					b.WriteString(" " + kdlQuote(arg))
				}
			}
			b.WriteString("\n")
		}

		b.WriteString("    }")
		if comment != "" {
			b.WriteString(" // " + comment)
		}
		b.WriteString("\n")
	}

	if config.Ambxst != nil {
		if config.Ambxst.System != nil {
			for name, kb := range config.Ambxst.System {
				addBind(kb, "Ambxst System: "+name)
			}
		}
		if config.Ambxst.Binds != nil {
			for name, kb := range config.Ambxst.Binds {
				addBind(kb, "Ambxst: "+name)
			}
		}
	}
	if config.Custom != nil {
		for i, kb := range config.Custom {
			addBind(kb, fmt.Sprintf("Custom Bind %d", i))
		}
	}

	b.WriteString("}\n")
	return b.String()
}

func tokenizeShell(s string) []string {
	s = strings.TrimSpace(s)
	if s == "" {
		return nil
	}
	var out []string
	var cur strings.Builder
	inQuote := byte(0)
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case inQuote != 0:
			if c == inQuote {
				inQuote = 0
			} else {
				cur.WriteByte(c)
			}
		case c == '"' || c == '\'':
			inQuote = c
		case c == ' ' || c == '\t':
			if cur.Len() > 0 {
				out = append(out, cur.String())
				cur.Reset()
			}
		default:
			cur.WriteByte(c)
		}
	}
	if cur.Len() > 0 {
		out = append(out, cur.String())
	}
	return out
}

func (g *Generator) GenerateWindowRules(rules []ipc.WindowRule) string {
	var b strings.Builder
	b.WriteString("// Generated by axctl (window rules)\n\n")

	for _, r := range rules {
		legacy := r.Match != "" && r.Rule != ""
		block := r.Float != nil || r.NoBlur != nil || r.NoShadow != nil ||
			r.Rounding != nil || r.BorderSize != nil || r.Pin != nil ||
			r.Fullscreen != nil || r.IdleInhibit != nil || r.NoScreenShare != nil ||
			r.Move != nil || r.Size != nil

		if legacy && !block {
			matchExpr := convertNiriMatch(r.Match)
			b.WriteString(fmt.Sprintf("window-rule {\n    match %s\n    %s\n}\n\n", matchExpr, r.Rule))
			continue
		}

		if r.Match == "" {
			continue
		}
		matchExpr := convertNiriMatch(r.Match)
		b.WriteString(fmt.Sprintf("window-rule {\n    match %s\n", matchExpr))

		if r.Float != nil {
			b.WriteString(fmt.Sprintf("    open-floating %s\n", boolKdl(*r.Float)))
		}
		if r.Fullscreen != nil {
			b.WriteString(fmt.Sprintf("    open-fullscreen %s\n", boolKdl(*r.Fullscreen)))
		}
		if r.Rounding != nil {
			b.WriteString(fmt.Sprintf("    geometry-corner-radius %d\n", *r.Rounding))
		}
		if r.BorderSize != nil {
			b.WriteString(fmt.Sprintf("    border {\n        width %d\n    }\n", *r.BorderSize))
		}
		if r.NoBlur != nil && *r.NoBlur {
			b.WriteString("    background-effect {\n        off\n    }\n")
		}
		if r.NoShadow != nil && *r.NoShadow {
			b.WriteString("    shadow {\n        off\n    }\n")
		}
		if r.Pin != nil && *r.Pin {
			b.WriteString("    // niri does not have a pin/sticky concept; map via open-on-workspace as needed\n")
		}
		if r.IdleInhibit != nil && *r.IdleInhibit {
			b.WriteString("    block-out-from \"screencast\"\n")
		}
		if r.NoScreenShare != nil && *r.NoScreenShare {
			b.WriteString("    block-out-from \"screencast\"\n")
		}
		if r.Move != nil && *r.Move != "" {
			b.WriteString(fmt.Sprintf("    // move %s (use per-output config in niri)\n", *r.Move))
		}
		if r.Size != nil && *r.Size != "" {
			b.WriteString(fmt.Sprintf("    // size %s (use default-window-width/height per-column)\n", *r.Size))
		}
		if r.Rule != "" {
			b.WriteString("    " + r.Rule + "\n")
		}
		b.WriteString("}\n\n")
	}
	return b.String()
}

func boolKdl(b bool) string {
	if b {
		return "true"
	}
	return "false"
}

func convertNiriMatch(m string) string {
	if m == "" {
		return ""
	}
	parts := strings.SplitN(m, ":", 2)
	if len(parts) < 2 {
		return kdlQuote(m)
	}
	prop, val := parts[0], strings.TrimSuffix(strings.TrimPrefix(strings.Trim(parts[1], "^$"), "("), ")")
	if prop == "class" {
		prop = "app-id"
	}
	if prop == "title" {
		return fmt.Sprintf("app-id=%s", kdlQuote("")) + " // title match below\n    title=" + kdlQuote(val)
	}
	return fmt.Sprintf("%s=%s", prop, kdlQuote(val))
}

func (g *Generator) GenerateLayerRules(rules []ipc.LayerRule) string {
	return "// Layer rules not supported in niri\n"
}

func (g *Generator) GenerateStartup(exec []string, execOnce []string) string {
	var b strings.Builder
	if len(exec) == 0 && len(execOnce) == 0 {
		return ""
	}
	b.WriteString("// Generated by axctl (startup)\n")
	b.WriteString("// niri has no exec-recurrent; exec-once maps to spawn-at-startup.\n\n")
	for _, cmd := range execOnce {
		if strings.TrimSpace(cmd) == "" {
			continue
		}
		b.WriteString(fmt.Sprintf("spawn-at-startup %s\n", kdlQuote(cmd)))
	}
	for _, cmd := range exec {
		if strings.TrimSpace(cmd) == "" {
			continue
		}
		b.WriteString(fmt.Sprintf("// niri does not re-run exec on reload; ignoring: %s\n", cmd))
	}
	return b.String()
}
