// Generated by go-wayland-scanner
// https://github.com/rajveermalviya/go-wayland/cmd/go-wayland-scanner
// XML file : /tmp/mangowc/protocols/dwl-ipc-unstable-v2.xml
//
// dwl_ipc_unstable_v2 Protocol Copyright:

package dwlipc

import "axctl/pkg/ipc/wayland/client"

// IpcManagerV2 : manage dwl state
//
// This interface is exposed as a global in wl_registry.
//
// Clients can use this interface to get a dwl_ipc_output.
// After binding the client will recieve the dwl_ipc_manager.tags and dwl_ipc_manager.layout events.
// The dwl_ipc_manager.tags and dwl_ipc_manager.layout events expose tags and layouts to the client.
type IpcManagerV2 struct {
	client.BaseProxy
	tagsHandler   IpcManagerV2TagsHandlerFunc
	layoutHandler IpcManagerV2LayoutHandlerFunc
}

// NewIpcManagerV2 : manage dwl state
//
// This interface is exposed as a global in wl_registry.
//
// Clients can use this interface to get a dwl_ipc_output.
// After binding the client will recieve the dwl_ipc_manager.tags and dwl_ipc_manager.layout events.
// The dwl_ipc_manager.tags and dwl_ipc_manager.layout events expose tags and layouts to the client.
func NewIpcManagerV2(ctx *client.Context) *IpcManagerV2 {
	zdwlIpcManagerV2 := &IpcManagerV2{}
	ctx.Register(zdwlIpcManagerV2)
	return zdwlIpcManagerV2
}

// Release : release dwl_ipc_manager
//
// Indicates that the client will not the dwl_ipc_manager object anymore.
// Objects created through this instance are not affected.
func (i *IpcManagerV2) Release() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// GetOutput : get a dwl_ipc_outout for a wl_output
//
// Get a dwl_ipc_outout for the specified wl_output.
func (i *IpcManagerV2) GetOutput(output *client.Output) (*IpcOutputV2, error) {
	id := NewIpcOutputV2(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], output.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// IpcManagerV2TagsEvent : Announces tag amount
//
// This event is sent after binding.
// A roundtrip after binding guarantees the client recieved all tags.
type IpcManagerV2TagsEvent struct {
	Amount uint32
}
type IpcManagerV2TagsHandlerFunc func(IpcManagerV2TagsEvent)

// SetTagsHandler : sets handler for IpcManagerV2TagsEvent
func (i *IpcManagerV2) SetTagsHandler(f IpcManagerV2TagsHandlerFunc) {
	i.tagsHandler = f
}

// IpcManagerV2LayoutEvent : Announces a layout
//
// This event is sent after binding.
// A roundtrip after binding guarantees the client recieved all layouts.
type IpcManagerV2LayoutEvent struct {
	Name string
}
type IpcManagerV2LayoutHandlerFunc func(IpcManagerV2LayoutEvent)

// SetLayoutHandler : sets handler for IpcManagerV2LayoutEvent
func (i *IpcManagerV2) SetLayoutHandler(f IpcManagerV2LayoutHandlerFunc) {
	i.layoutHandler = f
}

func (i *IpcManagerV2) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.tagsHandler == nil {
			return
		}
		var e IpcManagerV2TagsEvent
		l := 0
		e.Amount = client.Uint32(data[l : l+4])
		l += 4

		i.tagsHandler(e)
	case 1:
		if i.layoutHandler == nil {
			return
		}
		var e IpcManagerV2LayoutEvent
		l := 0
		nameLen := client.PaddedLen(int(client.Uint32(data[l : l+4])))
		l += 4
		e.Name = client.String(data[l : l+nameLen])
		l += nameLen

		i.layoutHandler(e)
	}
}

// IpcOutputV2 : control dwl output
//
// Observe and control a dwl output.
//
// Events are double-buffered:
// Clients should cache events and redraw when a dwl_ipc_output.frame event is sent.
//
// Request are not double-buffered:
// The compositor will update immediately upon request.
type IpcOutputV2 struct {
	client.BaseProxy
	toggleVisibilityHandler IpcOutputV2ToggleVisibilityHandlerFunc
	activeHandler           IpcOutputV2ActiveHandlerFunc
	tagHandler              IpcOutputV2TagHandlerFunc
	layoutHandler           IpcOutputV2LayoutHandlerFunc
	titleHandler            IpcOutputV2TitleHandlerFunc
	appidHandler            IpcOutputV2AppidHandlerFunc
	layoutSymbolHandler     IpcOutputV2LayoutSymbolHandlerFunc
	frameHandler            IpcOutputV2FrameHandlerFunc
	fullscreenHandler       IpcOutputV2FullscreenHandlerFunc
	floatingHandler         IpcOutputV2FloatingHandlerFunc
	xHandler                IpcOutputV2XHandlerFunc
	yHandler                IpcOutputV2YHandlerFunc
	widthHandler            IpcOutputV2WidthHandlerFunc
	heightHandler           IpcOutputV2HeightHandlerFunc
	lastLayerHandler        IpcOutputV2LastLayerHandlerFunc
	kbLayoutHandler         IpcOutputV2KbLayoutHandlerFunc
	keymodeHandler          IpcOutputV2KeymodeHandlerFunc
	scalefactorHandler      IpcOutputV2ScalefactorHandlerFunc
}

// NewIpcOutputV2 : control dwl output
//
// Observe and control a dwl output.
//
// Events are double-buffered:
// Clients should cache events and redraw when a dwl_ipc_output.frame event is sent.
//
// Request are not double-buffered:
// The compositor will update immediately upon request.
func NewIpcOutputV2(ctx *client.Context) *IpcOutputV2 {
	zdwlIpcOutputV2 := &IpcOutputV2{}
	ctx.Register(zdwlIpcOutputV2)
	return zdwlIpcOutputV2
}

// Release : release dwl_ipc_outout
//
// Indicates to that the client no longer needs this dwl_ipc_output.
func (i *IpcOutputV2) Release() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetTags : Set the active tags of this output
//
//	tagmask: bitmask of the tags that should be set.
//	toggleTagset: toggle the selected tagset, zero for invalid, nonzero for valid.
func (i *IpcOutputV2) SetTags(tagmask, toggleTagset uint32) error {
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(tagmask))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(toggleTagset))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetClientTags : Set the tags of the focused client.
//
// The tags are updated as follows:
// new_tags = (current_tags AND and_tags) XOR xor_tags
func (i *IpcOutputV2) SetClientTags(andTags, xorTags uint32) error {
	const opcode = 2
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(andTags))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(xorTags))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetLayout : Set the layout of this output
//
//	index: index of a layout recieved by dwl_ipc_manager.layout
func (i *IpcOutputV2) SetLayout(index uint32) error {
	const opcode = 3
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(index))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Quit : Quit mango
// This request allows clients to instruct the compositor to quit mango.
func (i *IpcOutputV2) Quit() error {
	const opcode = 4
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Dispatch : Set the active tags of this output
//
//	dispatch: dispatch name.
//	arg1: arg1.
//	arg2: arg2.
//	arg3: arg3.
//	arg4: arg4.
//	arg5: arg5.
func (i *IpcOutputV2) DispatchCmd(dispatch, arg1, arg2, arg3, arg4, arg5 string) error {
	const opcode = 5
	dispatchLen := client.PaddedLen(len(dispatch) + 1)
	arg1Len := client.PaddedLen(len(arg1) + 1)
	arg2Len := client.PaddedLen(len(arg2) + 1)
	arg3Len := client.PaddedLen(len(arg3) + 1)
	arg4Len := client.PaddedLen(len(arg4) + 1)
	arg5Len := client.PaddedLen(len(arg5) + 1)
	_reqBufLen := 8 + (4 + dispatchLen) + (4 + arg1Len) + (4 + arg2Len) + (4 + arg3Len) + (4 + arg4Len) + (4 + arg5Len)
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutString(_reqBuf[l:l+(4+dispatchLen)], dispatch)
	l += (4 + dispatchLen)
	client.PutString(_reqBuf[l:l+(4+arg1Len)], arg1)
	l += (4 + arg1Len)
	client.PutString(_reqBuf[l:l+(4+arg2Len)], arg2)
	l += (4 + arg2Len)
	client.PutString(_reqBuf[l:l+(4+arg3Len)], arg3)
	l += (4 + arg3Len)
	client.PutString(_reqBuf[l:l+(4+arg4Len)], arg4)
	l += (4 + arg4Len)
	client.PutString(_reqBuf[l:l+(4+arg5Len)], arg5)
	l += (4 + arg5Len)
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

type IpcOutputV2TagState uint32

// IpcOutputV2TagState :
const (
	// IpcOutputV2TagStateNone : no state
	IpcOutputV2TagStateNone IpcOutputV2TagState = 0
	// IpcOutputV2TagStateActive : tag is active
	IpcOutputV2TagStateActive IpcOutputV2TagState = 1
	// IpcOutputV2TagStateUrgent : tag has at least one urgent client
	IpcOutputV2TagStateUrgent IpcOutputV2TagState = 2
)

func (e IpcOutputV2TagState) Name() string {
	switch e {
	case IpcOutputV2TagStateNone:
		return "none"
	case IpcOutputV2TagStateActive:
		return "active"
	case IpcOutputV2TagStateUrgent:
		return "urgent"
	default:
		return ""
	}
}

func (e IpcOutputV2TagState) Value() string {
	switch e {
	case IpcOutputV2TagStateNone:
		return "0"
	case IpcOutputV2TagStateActive:
		return "1"
	case IpcOutputV2TagStateUrgent:
		return "2"
	default:
		return ""
	}
}

func (e IpcOutputV2TagState) String() string {
	return e.Name() + "=" + e.Value()
}

// IpcOutputV2ToggleVisibilityEvent : Toggle client visibilty
//
// Indicates the client should hide or show themselves.
// If the client is visible then hide, if hidden then show.
type IpcOutputV2ToggleVisibilityEvent struct{}
type IpcOutputV2ToggleVisibilityHandlerFunc func(IpcOutputV2ToggleVisibilityEvent)

// SetToggleVisibilityHandler : sets handler for IpcOutputV2ToggleVisibilityEvent
func (i *IpcOutputV2) SetToggleVisibilityHandler(f IpcOutputV2ToggleVisibilityHandlerFunc) {
	i.toggleVisibilityHandler = f
}

// IpcOutputV2ActiveEvent : Update the selected output.
//
// Indicates if the output is active. Zero is invalid, nonzero is valid.
type IpcOutputV2ActiveEvent struct {
	Active uint32
}
type IpcOutputV2ActiveHandlerFunc func(IpcOutputV2ActiveEvent)

// SetActiveHandler : sets handler for IpcOutputV2ActiveEvent
func (i *IpcOutputV2) SetActiveHandler(f IpcOutputV2ActiveHandlerFunc) {
	i.activeHandler = f
}

// IpcOutputV2TagEvent : Update the state of a tag.
//
// Indicates that a tag has been updated.
type IpcOutputV2TagEvent struct {
	Tag     uint32
	State   uint32
	Clients uint32
	Focused uint32
}
type IpcOutputV2TagHandlerFunc func(IpcOutputV2TagEvent)

// SetTagHandler : sets handler for IpcOutputV2TagEvent
func (i *IpcOutputV2) SetTagHandler(f IpcOutputV2TagHandlerFunc) {
	i.tagHandler = f
}

// IpcOutputV2LayoutEvent : Update the layout.
//
// Indicates a new layout is selected.
type IpcOutputV2LayoutEvent struct {
	Layout uint32
}
type IpcOutputV2LayoutHandlerFunc func(IpcOutputV2LayoutEvent)

// SetLayoutHandler : sets handler for IpcOutputV2LayoutEvent
func (i *IpcOutputV2) SetLayoutHandler(f IpcOutputV2LayoutHandlerFunc) {
	i.layoutHandler = f
}

// IpcOutputV2TitleEvent : Update the title.
//
// Indicates the title has changed.
type IpcOutputV2TitleEvent struct {
	Title string
}
type IpcOutputV2TitleHandlerFunc func(IpcOutputV2TitleEvent)

// SetTitleHandler : sets handler for IpcOutputV2TitleEvent
func (i *IpcOutputV2) SetTitleHandler(f IpcOutputV2TitleHandlerFunc) {
	i.titleHandler = f
}

// IpcOutputV2AppidEvent : Update the appid.
//
// Indicates the appid has changed.
type IpcOutputV2AppidEvent struct {
	Appid string
}
type IpcOutputV2AppidHandlerFunc func(IpcOutputV2AppidEvent)

// SetAppidHandler : sets handler for IpcOutputV2AppidEvent
func (i *IpcOutputV2) SetAppidHandler(f IpcOutputV2AppidHandlerFunc) {
	i.appidHandler = f
}

// IpcOutputV2LayoutSymbolEvent : Update the current layout symbol
//
// Indicates the layout has changed. Since layout symbols are dynamic.
// As opposed to the zdwl_ipc_manager.layout event, this should take precendence when displaying.
// You can ignore the zdwl_ipc_output.layout event.
type IpcOutputV2LayoutSymbolEvent struct {
	Layout string
}
type IpcOutputV2LayoutSymbolHandlerFunc func(IpcOutputV2LayoutSymbolEvent)

// SetLayoutSymbolHandler : sets handler for IpcOutputV2LayoutSymbolEvent
func (i *IpcOutputV2) SetLayoutSymbolHandler(f IpcOutputV2LayoutSymbolHandlerFunc) {
	i.layoutSymbolHandler = f
}

// IpcOutputV2FrameEvent : The update sequence is done.
//
// Indicates that a sequence of status updates have finished and the client should redraw.
type IpcOutputV2FrameEvent struct{}
type IpcOutputV2FrameHandlerFunc func(IpcOutputV2FrameEvent)

// SetFrameHandler : sets handler for IpcOutputV2FrameEvent
func (i *IpcOutputV2) SetFrameHandler(f IpcOutputV2FrameHandlerFunc) {
	i.frameHandler = f
}

// IpcOutputV2FullscreenEvent : Update fullscreen status
//
// Indicates if the selected client on this output is fullscreen.
type IpcOutputV2FullscreenEvent struct {
	IsFullscreen uint32
}
type IpcOutputV2FullscreenHandlerFunc func(IpcOutputV2FullscreenEvent)

// SetFullscreenHandler : sets handler for IpcOutputV2FullscreenEvent
func (i *IpcOutputV2) SetFullscreenHandler(f IpcOutputV2FullscreenHandlerFunc) {
	i.fullscreenHandler = f
}

// IpcOutputV2FloatingEvent : Update the floating status
//
// Indicates if the selected client on this output is floating.
type IpcOutputV2FloatingEvent struct {
	IsFloating uint32
}
type IpcOutputV2FloatingHandlerFunc func(IpcOutputV2FloatingEvent)

// SetFloatingHandler : sets handler for IpcOutputV2FloatingEvent
func (i *IpcOutputV2) SetFloatingHandler(f IpcOutputV2FloatingHandlerFunc) {
	i.floatingHandler = f
}

// IpcOutputV2XEvent : Update the x coordinates
//
// Indicates if x coordinates of the selected client.
type IpcOutputV2XEvent struct {
	X int32
}
type IpcOutputV2XHandlerFunc func(IpcOutputV2XEvent)

// SetXHandler : sets handler for IpcOutputV2XEvent
func (i *IpcOutputV2) SetXHandler(f IpcOutputV2XHandlerFunc) {
	i.xHandler = f
}

// IpcOutputV2YEvent : Update the y coordinates
//
// Indicates if y coordinates of the selected client.
type IpcOutputV2YEvent struct {
	Y int32
}
type IpcOutputV2YHandlerFunc func(IpcOutputV2YEvent)

// SetYHandler : sets handler for IpcOutputV2YEvent
func (i *IpcOutputV2) SetYHandler(f IpcOutputV2YHandlerFunc) {
	i.yHandler = f
}

// IpcOutputV2WidthEvent : Update the width
//
// Indicates if width of the selected client.
type IpcOutputV2WidthEvent struct {
	Width int32
}
type IpcOutputV2WidthHandlerFunc func(IpcOutputV2WidthEvent)

// SetWidthHandler : sets handler for IpcOutputV2WidthEvent
func (i *IpcOutputV2) SetWidthHandler(f IpcOutputV2WidthHandlerFunc) {
	i.widthHandler = f
}

// IpcOutputV2HeightEvent : Update the height
//
// Indicates if height of the selected client.
type IpcOutputV2HeightEvent struct {
	Height int32
}
type IpcOutputV2HeightHandlerFunc func(IpcOutputV2HeightEvent)

// SetHeightHandler : sets handler for IpcOutputV2HeightEvent
func (i *IpcOutputV2) SetHeightHandler(f IpcOutputV2HeightHandlerFunc) {
	i.heightHandler = f
}

// IpcOutputV2LastLayerEvent : last map layer.
//
// last map layer.
type IpcOutputV2LastLayerEvent struct {
	LastLayer string
}
type IpcOutputV2LastLayerHandlerFunc func(IpcOutputV2LastLayerEvent)

// SetLastLayerHandler : sets handler for IpcOutputV2LastLayerEvent
func (i *IpcOutputV2) SetLastLayerHandler(f IpcOutputV2LastLayerHandlerFunc) {
	i.lastLayerHandler = f
}

// IpcOutputV2KbLayoutEvent : current keyboard layout.
//
// current keyboard layout.
type IpcOutputV2KbLayoutEvent struct {
	KbLayout string
}
type IpcOutputV2KbLayoutHandlerFunc func(IpcOutputV2KbLayoutEvent)

// SetKbLayoutHandler : sets handler for IpcOutputV2KbLayoutEvent
func (i *IpcOutputV2) SetKbLayoutHandler(f IpcOutputV2KbLayoutHandlerFunc) {
	i.kbLayoutHandler = f
}

// IpcOutputV2KeymodeEvent : current keybind mode.
//
// current keybind mode.
type IpcOutputV2KeymodeEvent struct {
	Keymode string
}
type IpcOutputV2KeymodeHandlerFunc func(IpcOutputV2KeymodeEvent)

// SetKeymodeHandler : sets handler for IpcOutputV2KeymodeEvent
func (i *IpcOutputV2) SetKeymodeHandler(f IpcOutputV2KeymodeHandlerFunc) {
	i.keymodeHandler = f
}

// IpcOutputV2ScalefactorEvent : scale factor of monitor.
//
// scale factor of monitor.
type IpcOutputV2ScalefactorEvent struct {
	Scalefactor uint32
}
type IpcOutputV2ScalefactorHandlerFunc func(IpcOutputV2ScalefactorEvent)

// SetScalefactorHandler : sets handler for IpcOutputV2ScalefactorEvent
func (i *IpcOutputV2) SetScalefactorHandler(f IpcOutputV2ScalefactorHandlerFunc) {
	i.scalefactorHandler = f
}

func (i *IpcOutputV2) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.toggleVisibilityHandler == nil {
			return
		}
		var e IpcOutputV2ToggleVisibilityEvent

		i.toggleVisibilityHandler(e)
	case 1:
		if i.activeHandler == nil {
			return
		}
		var e IpcOutputV2ActiveEvent
		l := 0
		e.Active = client.Uint32(data[l : l+4])
		l += 4

		i.activeHandler(e)
	case 2:
		if i.tagHandler == nil {
			return
		}
		var e IpcOutputV2TagEvent
		l := 0
		e.Tag = client.Uint32(data[l : l+4])
		l += 4
		e.State = client.Uint32(data[l : l+4])
		l += 4
		e.Clients = client.Uint32(data[l : l+4])
		l += 4
		e.Focused = client.Uint32(data[l : l+4])
		l += 4

		i.tagHandler(e)
	case 3:
		if i.layoutHandler == nil {
			return
		}
		var e IpcOutputV2LayoutEvent
		l := 0
		e.Layout = client.Uint32(data[l : l+4])
		l += 4

		i.layoutHandler(e)
	case 4:
		if i.titleHandler == nil {
			return
		}
		var e IpcOutputV2TitleEvent
		l := 0
		titleLen := client.PaddedLen(int(client.Uint32(data[l : l+4])))
		l += 4
		e.Title = client.String(data[l : l+titleLen])
		l += titleLen

		i.titleHandler(e)
	case 5:
		if i.appidHandler == nil {
			return
		}
		var e IpcOutputV2AppidEvent
		l := 0
		appidLen := client.PaddedLen(int(client.Uint32(data[l : l+4])))
		l += 4
		e.Appid = client.String(data[l : l+appidLen])
		l += appidLen

		i.appidHandler(e)
	case 6:
		if i.layoutSymbolHandler == nil {
			return
		}
		var e IpcOutputV2LayoutSymbolEvent
		l := 0
		layoutLen := client.PaddedLen(int(client.Uint32(data[l : l+4])))
		l += 4
		e.Layout = client.String(data[l : l+layoutLen])
		l += layoutLen

		i.layoutSymbolHandler(e)
	case 7:
		if i.frameHandler == nil {
			return
		}
		var e IpcOutputV2FrameEvent

		i.frameHandler(e)
	case 8:
		if i.fullscreenHandler == nil {
			return
		}
		var e IpcOutputV2FullscreenEvent
		l := 0
		e.IsFullscreen = client.Uint32(data[l : l+4])
		l += 4

		i.fullscreenHandler(e)
	case 9:
		if i.floatingHandler == nil {
			return
		}
		var e IpcOutputV2FloatingEvent
		l := 0
		e.IsFloating = client.Uint32(data[l : l+4])
		l += 4

		i.floatingHandler(e)
	case 10:
		if i.xHandler == nil {
			return
		}
		var e IpcOutputV2XEvent
		l := 0
		e.X = int32(client.Uint32(data[l : l+4]))
		l += 4

		i.xHandler(e)
	case 11:
		if i.yHandler == nil {
			return
		}
		var e IpcOutputV2YEvent
		l := 0
		e.Y = int32(client.Uint32(data[l : l+4]))
		l += 4

		i.yHandler(e)
	case 12:
		if i.widthHandler == nil {
			return
		}
		var e IpcOutputV2WidthEvent
		l := 0
		e.Width = int32(client.Uint32(data[l : l+4]))
		l += 4

		i.widthHandler(e)
	case 13:
		if i.heightHandler == nil {
			return
		}
		var e IpcOutputV2HeightEvent
		l := 0
		e.Height = int32(client.Uint32(data[l : l+4]))
		l += 4

		i.heightHandler(e)
	case 14:
		if i.lastLayerHandler == nil {
			return
		}
		var e IpcOutputV2LastLayerEvent
		l := 0
		lastLayerLen := client.PaddedLen(int(client.Uint32(data[l : l+4])))
		l += 4
		e.LastLayer = client.String(data[l : l+lastLayerLen])
		l += lastLayerLen

		i.lastLayerHandler(e)
	case 15:
		if i.kbLayoutHandler == nil {
			return
		}
		var e IpcOutputV2KbLayoutEvent
		l := 0
		kbLayoutLen := client.PaddedLen(int(client.Uint32(data[l : l+4])))
		l += 4
		e.KbLayout = client.String(data[l : l+kbLayoutLen])
		l += kbLayoutLen

		i.kbLayoutHandler(e)
	case 16:
		if i.keymodeHandler == nil {
			return
		}
		var e IpcOutputV2KeymodeEvent
		l := 0
		keymodeLen := client.PaddedLen(int(client.Uint32(data[l : l+4])))
		l += 4
		e.Keymode = client.String(data[l : l+keymodeLen])
		l += keymodeLen

		i.keymodeHandler(e)
	case 17:
		if i.scalefactorHandler == nil {
			return
		}
		var e IpcOutputV2ScalefactorEvent
		l := 0
		e.Scalefactor = client.Uint32(data[l : l+4])
		l += 4

		i.scalefactorHandler(e)
	}
}
