package hyprland

import (
	"fmt"
	"strings"

	"axctl/pkg/ipc"
)

type Generator struct{}

// NewGenerator returns a new instance of the Hyprland config generator
func NewGenerator() *Generator {
	return &Generator{}
}

func formatHyprlandColor(hexStr string) string {
	if hexStr == "" {
		return "rgba(00000000)"
	}
	if strings.HasPrefix(hexStr, "#") {
		hexStr = hexStr[1:]
	}

	r, g, b, a := "00", "00", "00", "ff"
	if len(hexStr) >= 6 {
		r = hexStr[0:2]
		g = hexStr[2:4]
		b = hexStr[4:6]
	}
	if len(hexStr) == 8 {
		a = hexStr[6:8]
	}

	return fmt.Sprintf("rgba(%s%s%s%s)", r, g, b, a)
}

func parseColorString(str string) (string, string) {
	if str == "" {
		return "", ""
	}
	parts := strings.Fields(str)
	var colors []string
	var angle string

	for _, part := range parts {
		if strings.HasSuffix(part, "deg") {
			angle = part
		} else if strings.HasPrefix(part, "#") || len(part) == 6 || len(part) == 8 {
			colors = append(colors, formatHyprlandColor(part))
		}
	}

	colorStr := strings.Join(colors, " ")
	return colorStr, angle
}

func (g *Generator) GenerateAppearance(config ipc.ConfigAppearance) string {
	var out strings.Builder

	out.WriteString("# Generated by axctl ConfigGenerator\n")
	out.WriteString("# Do not edit manually!\n\n")

	out.WriteString("general {\n")
	if config.Gaps != nil {
		if config.Gaps.Inner != nil {
			out.WriteString(fmt.Sprintf("    gaps_in = %d\n", *config.Gaps.Inner))
		}
		if config.Gaps.Outer != nil {
			out.WriteString(fmt.Sprintf("    gaps_out = %d\n", *config.Gaps.Outer))
		}
	}
	if config.Border != nil {
		if config.Border.Width != nil {
			out.WriteString(fmt.Sprintf("    border_size = %d\n", *config.Border.Width))
		}
		if config.Border.ActiveColor != nil {
			colors, angle := parseColorString(*config.Border.ActiveColor)
			if colors != "" {
				if angle != "" {
					colors += " " + angle
				}
				out.WriteString(fmt.Sprintf("    col.active_border = %s\n", colors))
			}
		}
		if config.Border.InactiveColor != nil {
			colors, angle := parseColorString(*config.Border.InactiveColor)
			if colors != "" {
				if angle != "" {
					colors += " " + angle
				}
				out.WriteString(fmt.Sprintf("    col.inactive_border = %s\n", colors))
			}
		}
	}
	out.WriteString("}\n\n")

	out.WriteString("decoration {\n")
	if config.Border != nil && config.Border.Rounding != nil {
		out.WriteString(fmt.Sprintf("    rounding = %d\n", *config.Border.Rounding))
	}
	if config.Opacity != nil {
		if config.Opacity.Active != nil {
			out.WriteString(fmt.Sprintf("    active_opacity = %.2f\n", *config.Opacity.Active))
		}
		if config.Opacity.Inactive != nil {
			out.WriteString(fmt.Sprintf("    inactive_opacity = %.2f\n", *config.Opacity.Inactive))
		}
	}

	if config.Shadow != nil && config.Shadow.Enabled != nil {
		out.WriteString(fmt.Sprintf("    drop_shadow = %v\n", *config.Shadow.Enabled))
		if config.Shadow.Size != nil {
			out.WriteString(fmt.Sprintf("    shadow_range = %d\n", *config.Shadow.Size))
		}
		if config.Shadow.Color != nil {
			colorStr, _ := parseColorString(*config.Shadow.Color)
			if colorStr != "" {
				out.WriteString(fmt.Sprintf("    col.shadow = %s\n", colorStr))
			}
		}
	}

	out.WriteString("    blur {\n")
	if config.Blur != nil {
		if config.Blur.Enabled != nil {
			enabled := "false"
			if *config.Blur.Enabled {
				enabled = "true"
			}
			out.WriteString(fmt.Sprintf("        enabled = %s\n", enabled))
		}
		if config.Blur.Size != nil {
			out.WriteString(fmt.Sprintf("        size = %d\n", *config.Blur.Size))
		}
		if config.Blur.Passes != nil {
			out.WriteString(fmt.Sprintf("        passes = %d\n", *config.Blur.Passes))
		}
	}
	out.WriteString("    }\n")
	out.WriteString("}\n\n")

	if config.Animations != nil && config.Animations.Enabled != nil {
		out.WriteString("animations {\n")
		enabled := "false"
		if *config.Animations.Enabled {
			enabled = "true"
		}
		out.WriteString(fmt.Sprintf("    enabled = %s\n", enabled))
		out.WriteString("}\n")
	}

	return out.String()
}

func formatModifiers(mods []string) string {
	if len(mods) == 0 {
		return ""
	}
	return strings.Join(mods, " ")
}

func (g *Generator) GenerateKeybinds(config ipc.ConfigKeybinds) string {
	var out strings.Builder
	out.WriteString("# Generated by axctl ConfigGenerator (Keybinds)\n")
	out.WriteString("# Do not edit manually!\n\n")

	addBind := func(kb ipc.Keybind, comment string) {
		if !kb.Enabled || kb.Key == "" {
			return
		}
		mod := formatModifiers(kb.Modifiers)
		dispatcher := kb.Dispatcher
		if dispatcher == "" {
			dispatcher = "exec"
		}
		arg := kb.Argument
		
		// Map generic modifiers to Hyprland's
		mod = strings.ReplaceAll(mod, "SUPER", "SUPER")
		mod = strings.ReplaceAll(mod, "CTRL", "CTRL")
		mod = strings.ReplaceAll(mod, "ALT", "ALT")
		mod = strings.ReplaceAll(mod, "SHIFT", "SHIFT")

		line := fmt.Sprintf("bind = %s, %s, %s, %s", mod, kb.Key, dispatcher, arg)
		if comment != "" {
			line += fmt.Sprintf(" # %s", comment)
		}
		out.WriteString(line + "\n")
	}

	if config.Ambxst != nil {
		if config.Ambxst.System != nil {
			for name, kb := range config.Ambxst.System {
				addBind(kb, fmt.Sprintf("Ambxst System: %s", name))
			}
		}
		if config.Ambxst.Binds != nil {
			for name, kb := range config.Ambxst.Binds {
				addBind(kb, fmt.Sprintf("Ambxst: %s", name))
			}
		}
	}

	if config.Custom != nil {
		for i, kb := range config.Custom {
			addBind(kb, fmt.Sprintf("Custom Bind %d", i))
		}
	}

	return out.String()
}

func (g *Generator) GenerateWindowRules(rules []ipc.WindowRule) string {
	var out strings.Builder
	out.WriteString("# Generated by axctl ConfigGenerator (Window Rules)\n")
	out.WriteString("# Do not edit manually!\n\n")

	for _, r := range rules {
		if r.Match != "" && r.Rule != "" {
			out.WriteString(fmt.Sprintf("windowrulev2 = %s, %s\n", r.Rule, r.Match))
		}
	}

	return out.String()
}
